version: '3.8'
services:
# portainer -------------------------
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${configPath}/portainer/:/data'
    ports:
      - 9443:9443
    restart: unless-stopped
# gluetun -------------------------
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - '${configPath}/gluetun/custom.ovpn:/gluetun/custom.ovpn:ro'
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.ovpn
      - OPENVPN_USER=openVpnUserName
      - OPENVPN_PASSWORD=openVpnPassword
      - FIREWALL_VPN_INPUT_PORTS=8999,38406 # comma separated ports for port forwarding (qBittorrent etc.)
    ports:
      # qbittorrent
      - 8208:8080
      - 6881:6881
      - 6881:6881/udp
      # rdtclient
      - 6500:6500
      # Jackett
      - 9117:9117
    restart: unless-stopped
# qbittorrent -------------------------
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - '${configPath}/qBittorrent/:/config'
      - '${downloadPath}/:/downloads'
    network_mode: service:gluetun
    restart: unless-stopped
# Debrid Client -------------------------
  rdtclient:
    image: rogerfar/rdtclient:latest
    container_name: rdtclient
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - '${downloadsPath}/:/data/downloads:rw'
      - '${configPath}/rdtclient/:/data/db:rw'
    # ports:
    #     - '6500:6500'
    network_mode: service:gluetun
    restart: unless-stopped
# Sonarr -------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - '${configPath}/sonarr/:/config'
      - '${tvSeriesPath}/:/tv'
      - '${downloadsPath}/:/downloads'
    ports:
      - 8989:8989
    restart: unless-stopped
# Radarr -------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - '${configPath}/radarr/:/config'
      - '${moviesPath}/:/movies'
      - '${downloadsPath}/:/downloads'
    ports:
      - 7878:7878
    restart: unless-stopped
# Overseerr -------------------------
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - '${configPath}/overseerr/:/config'
    ports:
      - 5055:5055
    restart: unless-stopped
# Jackett -------------------------
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - '${configPath}/jackett/config/:/config'
      - '${drivePath}/:/downloads'
      - '/etc/localtime:/etc/localtime:ro'
      - '${configPath}/jackett/shared:/shared'
    # ports:
    #     - 9117:9117
    restart: unless-stopped
# Bazarr -------------------------
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - '${configPath}/bazaar/:/config'
      - '${moviesPath}/:/movies'
      - '${tvSeriesPath}/:/tv'
    ports:
      - 6767:6767
    restart: unless-stopped
# Jellyfin -------------------------
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - JELLYFIN_PublishedServerUrl=192.168.1.250 #optional
    volumes:
      - '${configPath}/jellyfin/:/config'
      - '${tvSeriesPath}/:/data/tvshows'
      - '${moviesPath}/:/data/movies'
    ports:
      - 8096:8096
    restart: unless-stopped
